### ISSUE TITLE
新版用springboot-starter用不了feign自动注入   旧版mongoDB无法禁用 启动就报错

### ISSUE THREAD

**Issue by kiradesui** [Dromara/hmily#100]
2.0.0的版本用hmily-spring-boot-starter-springcloud的话 并且我不是用mongoDB 每次启动都要报错一下 ,如果禁用mongoDB又启动不了
2.0.5的版本用hmily-spring-boot-starter-springcloud的话 用feign自动注入会注入失败 出现直接启动报错 这些都是bug

---->mongoDB报错
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:62)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:126)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:114)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:59)
	at com.mongodb.connection.SocketStream.open(SocketStream.java:57)
	... 3 common frames omitted

------>无法注入报错
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'orderService': Unsatisfied dependency expressed through field 'webSocketClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cn.focus.pay.modular.consumer.webSocketClient': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:587)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:373)

**Comment by yu199195** [comment]
建议看下demo，如果是springboot 排除掉mongo 启动类，或者，排除掉mongo 的start包

**Comment by kiradesui** [comment]
2.0.5无法注入feign又是什么情况??用旧版本就可以...

**Comment by yu199195** [comment]
2.0.5 需要更高的spring cloud 版本，

**Comment by kiradesui** [comment]
好的 谢谢

**Comment by www-hulinbo-com** [comment]
我在使用2.0.5版本时也出现了 通过feign调用的接口 无法注入IOC容器，spring cloud版本与demo项目中的一致，demo能正这是什么情况

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'inventoryService': Unsatisfied dependency expressed through field 'accountService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'werty.service.clent.AccountService': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException

**Comment by www-hulinbo-com** [comment]
好像是hmily-spring-boot-starter-springcloud有点问题   我换成hmily-springcloud后就行了
