### ISSUE TITLE
hmily-spring-boot-starter-dubbo使用@Reference报错

### ISSUE THREAD

**Issue by ankoye** [Dromara/hmily#120]
使用@Reference远程调用导致报错bean name乱码了，无法完成confirm或cancel：
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'uService' available // skuService乱码了
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:808) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1279) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:297) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:276) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1114) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.dromara.hmily.core.helper.SpringBeanUtils.getByName(SpringBeanUtils.java:72) ~[hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at org.dromara.hmily.core.helper.SpringBeanUtils.getBean(SpringBeanUtils.java:64) ~[hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at org.dromara.hmily.core.reflect.HmilyReflector.execute(HmilyReflector.java:66) ~[hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at org.dromara.hmily.core.reflect.HmilyReflector.executor(HmilyReflector.java:54) ~[hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at org.dromara.hmily.core.service.executor.HmilyTransactionExecutor.confirm(HmilyTransactionExecutor.java:149) ~[hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at org.dromara.hmily.core.service.handler.StarterHmilyTransactionHandler.lambda$handler$1(StarterHmilyTransactionHandler.java:82) [hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at org.dromara.hmily.core.disruptor.handler.HmilyConsumerTransactionDataHandler.executor(HmilyConsumerTransactionDataHandler.java:28) ~[hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at org.dromara.hmily.core.disruptor.handler.HmilyConsumerTransactionDataHandler.executor(HmilyConsumerTransactionDataHandler.java:13) ~[hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at org.dromara.hmily.core.disruptor.DisruptorConsumer.onEvent(DisruptorConsumer.java:40) ~[hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at org.dromara.hmily.core.disruptor.DisruptorConsumer.onEvent(DisruptorConsumer.java:29) ~[hmily-core-2.0.6-RELEASE.jar:2.0.6-RELEASE]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_221]

目前使用xml配置reference解决了

**Comment by yu199195** [comment]
这个是你dubbo 的问题吧，dubbo-starter的问题

**Comment by ankoye** [comment]
> 这个是你dubbo 的问题吧，dubbo-starter的问题

好的
