### ISSUE TITLE
tcc在使用redis作为存储时会报HmilyRespositoryException,这个异常在confirm调用时产生。使用2.1.1版本

### ISSUE THREAD

**Issue by vr139180** [dromara/hmily#244]
[15:37:09.203] INFO  com.bluememo.shopcenter.inventory.services.impl.ShopInventoryServiceImpl 211 confirmDeduCancelInventory - cancelDeduInventory:{"code":"0","nokey":[]}
Exception in thread "hmily-hmily-log-disruptor0-34" org.dromara.hmily.repository.spi.exception.HmilyRepositoryException: hmily repository have exception
        at org.dromara.hmily.core.repository.HmilyRepositoryFacade.checkRows(HmilyRepositoryFacade.java:175)
        at org.dromara.hmily.core.repository.HmilyRepositoryFacade.updateHmilyParticipantStatus(HmilyRepositoryFacade.java:105)
        at org.dromara.hmily.core.repository.HmilyRepositoryDispatcher.doDispatcher(HmilyRepositoryDispatcher.java:68)
        at org.dromara.hmily.core.disruptor.handler.HmilyRepositoryDataHandler.lambda$executor$0(HmilyRepositoryDataHandler.java:36)
        at org.dromara.hmily.core.disruptor.handler.HmilyRepositoryDataHandler$$Lambda$518/163312297.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by yu199195** [comment]
提供详细点的

**Comment by vr139180** [comment]
只有这一段相关的日志

**Comment by vanniuner** [comment]
我也遇到了，没有结果了？
