### ISSUE TITLE
读取user.dir目录下配置文件直接报异常

### ISSUE THREAD

**Issue by xz1367** [dromara/hmily#288]
项目启动时，读取user.dir目录下hmily.yml文件，文件存在时，直接抛出了异常，

2021-01-23 16:03:38.474 ERROR 728900 --- [           main] o.d.hmily.core.bootstrap.HmilyBootstrap  :  hmily init exception:

org.dromara.hmily.config.api.exception.ConfigException: ConfigLoader:loader config error,error file path:/usr/local/java/im/im-service/im-payment-service/hmily.yml
	at org.dromara.hmily.config.loader.ServerConfigLoader.load(ServerConfigLoader.java:54)
	at org.dromara.hmily.config.loader.ConfigLoaderServer.load(ConfigLoaderServer.java:38)
	at org.dromara.hmily.core.bootstrap.HmilyBootstrap.start(HmilyBootstrap.java:72)
	at org.dromara.hmily.spring.HmilyApplicationContextAware.setApplicationContext(HmilyApplicationContextAware.java:42)

而没有去加载文件，逻辑应该存在错误。

![image](https://user-images.githubusercontent.com/1396406/105573083-1c86b580-5d96-11eb-9154-a4863a0d4afa.png)

**Comment by xz1367** [comment]
public class ServerConfigLoader implements ConfigLoader<HmilyServer> {

    private final YamlPropertyLoader propertyLoader = new YamlPropertyLoader();

    @Override
    public void load(final Supplier<Context> context, final LoaderHandler<HmilyServer> handler) {
        String filePath = System.getProperty("hmily.conf");
        File configFile;
        if (StringUtils.isBlank(filePath)) {
            String dirPath = getDirGlobal();
            configFile = new File(dirPath);
            if (configFile.exists()) {
                filePath = dirPath;
                throw new ConfigException("ConfigLoader:loader config error,error file path:" + filePath);
            } else {
                //Mainly used for development environment。
                ClassLoader loader = ConfigLoader.class.getClassLoader();
                URL url = loader.getResource("hmily.yml");
                if (url != null) {
                    filePath = url.getFile();
                    configFile = new File(filePath);
                } else {
                    throw new ConfigException("ConfigLoader:loader config error,error file path:" + filePath);
                }
            }
        } else {
            configFile = new File(filePath);
            if (!configFile.exists()) {
                throw new ConfigException("ConfigLoader:loader config error,error file path:" + filePath);
            }
        }
        try (FileInputStream inputStream = new FileInputStream(configFile)) {
            List<PropertyKeySource<?>> propertyKeySources = propertyLoader.load(filePath, inputStream);
            OriginalConfigLoader original = new OriginalConfigLoader();
            againLoad(() -> context.get().with(propertyKeySources, original), handler, HmilyServer.class);
        } catch (IOException e) {
            throw new ConfigException("ConfigLoader:loader config error,file path:" + filePath);
        }
    }


在这个判断中：
if (configFile.exists()) {
                filePath = dirPath;
                throw new ConfigException("ConfigLoader:loader config error,error file path:" + filePath);
            }
存在应该是加载，这里抛出了异常，导致无法加载。
