### ISSUE TITLE
facade接口使用有问题

### ISSUE THREAD

**Issue by houyangkun** [Dromara/hmily#74]
java.lang.NoSuchMethodException: com.qlbt.facade.member.HomeWorkFacade.$echo(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1786)
	at org.dromara.hmily.dubbo.filter.DubboHmilyTransactionFilter.invoke(DubboHmilyTransactionFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:74)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:47)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:73)

**Comment by yu199195** [comment]
你的接口是什么样的，请提供，这样我是没办法看的

**Comment by shenyanming95** [comment]
我的问题跟他一样，是在使用注解时分别在接口和接口实现类都使用了@Hmily，但是在执行try操作的时候会报空指针异常，我跟了下源码，是因为获取到接口上的注解，所以cofirmMethod和cancelMethod属性都为空，这是我的接口定义情况：
```java
public interface IIcbcBank {
    @Hmily
    boolean transferOut(AccountDTO accountDTO);

}
```

```java
@Service
public class IcbcBankImpl  implements IIcbcBank {
    @Override
    @Hmily(confirmMethod = "reduceMoney", cancelMethod = "increaseMoney")
    @Transactional(rollbackFor = Exception.class)
    public boolean transferOut(AccountDTO accountDTO) {

}
}
```
异常就是空指针了，因为spring好像会取接口上的注解，而不会取实现类的注解

**Comment by yu199195** [comment]
你是dubbo还是springcloud？ 请看看demo
