### ISSUE TITLE
Spring Cloud + Nacos 最新版本 NullPointerException

### ISSUE THREAD

**Issue by biezhi** [Dromara/hmily#99]
您好，以下是我使用的各个组件的情况：

- jdk: `1.8`
- hmily-spring-boot-starter-springcloud: `2.0.5-RELEASE`
- spring-cloud: `Greenwich.SR2`
- Nacos(SpringCloudAlibaba):  `0.9.0.RELEASE`
- OS: `Mac OS X 10.14.6`

我按照示例中的代码搭建了 `account`、`stock`、`order` 的服务，在启动的时候报如下错误：

```java
Caused by: java.lang.NullPointerException: null
	at org.dromara.hmily.core.helper.SpringBeanUtils.getBean(SpringBeanUtils.java:62)
	at org.dromara.hmily.core.schedule.HmilyTransactionSelfRecoveryScheduled.onApplicationEvent(HmilyTransactionSelfRecoveryScheduled.java:75)
	at org.dromara.hmily.core.schedule.HmilyTransactionSelfRecoveryScheduled.onApplicationEvent(HmilyTransactionSelfRecoveryScheduled.java:52)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:408)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:136)
	at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:101)
	at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:145)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignContext.getInstance(TraceFeignContext.java:46)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.get(FeignClientFactoryBean.java:220)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.feign(FeignClientFactoryBean.java:84)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:257)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:247)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	... 61 common frames omitted
```

打断点调试后发现是 `SpringBeanUtils` 类的 `bean = cfgContext.getBean(type);` 这一行 `cfgContext` 为 `null`，这里的静态变量应该是 `HmilyTransactionBootstrap#setApplicationContext` 设置值的，但是 `HmilyTransactionSelfRecoveryScheduled#onApplicationEvent` 方法优先执行了，导致 cfgContext 一直是 `null` 启动无法通过。

**Comment by yu199195** [comment]
为什么，ApplicationContextAware 会比  ApplicationListener<ContextRefreshedEvent> 后执行呢？

**Comment by GitByRen** [comment]
我也遇到了这个问题，怎么解决呢？

**Comment by ElanZh** [comment]
我也是，不知道是不是因为feignClient导致的spring发布event，从而导致ApplicationLisenter先执行了，
有没有懂得大佬能解释一下

**Comment by ElanZh** [comment]
> 
> 
> 我也是，不知道是不是因为feignClient导致的spring发布event，从而导致ApplicationLisenter先执行了，
> 有没有懂得大佬能解释一下

- JDK：```openjdk-11```
- Regist：```Consul-1.4.2```
- Hmily：```2.0.5```
- spring-boot-starter-parent：```2.1.9.RELEASE```
- spring-cloud-starter-openfeign：```2.1.3.RELEASE```

**Comment by yu199195** [comment]
随后我来看一下

**Comment by www-hulinbo-com** [comment]
我不确定我们是不是同样的问题，我的解决办法是 事务发起者使用hmily-springcloud依赖，配置的方式是采用.xml文件导入的方式。事务发起者和事务参与者的配置有点区别。
        我试过Java配置类或者hmily-spring-boot-starter-springcloud的自动配置，都会在Spring容器加载时出错，可能是其中的类的创建顺序有要求。
        希望对你有帮助。






在 2019-10-07 21:52:16，"GitByRen" <notifications@github.com> 写道：


我也遇到了这个问题，怎么解决呢？

**Comment by www-hulinbo-com** [comment]
我不确定我们是不是同样的问题，我的解决办法是 事务发起者使用hmily-springcloud依赖，配置的方式是采用.xml文件导入的方式。事务发起者和事务参与者的配置有点区别。
        我试过Java配置类或者hmily-spring-boot-starter-springcloud的自动配置，都会在Spring容器加载时出错，可能是其中的类的创建顺序有要求。
        希望对你有帮助。








在 2019-10-18 17:39:50，"ElanZh" <notifications@github.com> 写道：


我也是，不知道是不是因为feignClient导致的spring发布event，从而导致ApplicationLisenter先执行了，
有没有懂得大佬能解释一下

JDK：openjdk-11
Regist：Consul-1.4.2
Hmily：2.0.5
spring-boot-starter-parent：2.1.9.RELEASE
spring-cloud-starter-openfeign：2.1.3.RELEASE

**Comment by yu199195** [comment]
feignClient导致的spring发布event，从而导致ApplicationLisenter先执行了，我来调整一下顺序把

**Comment by yu199195** [comment]
在master分支已经修复了这个问题

**Comment by songhanlin** [comment]
> 在master分支已经修复了这个问题

修改的提交记录是哪个?
